# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: a
  steps:
  - checkout: self
    fetchDepth: 1
    path: zephyr
  - bash: |
      echo $(Build.Repository.Name)
      git log -5
      which bash
      ls
      ls /
      echo "-- export --"
      export
      echo "--- PWD ---"
      pwd
      pip3 install setuptools wheel
      pip3 install west
      export PATH=$HOME/.local/bin:$PATH
      source zephyr-env.sh
      west init -l . || true
      west update
      export CITOOLS=$(west list ci-tools -f"{abspath:18}")
      echo $CITOOLS
      sudo pip3 install -r ${CITOOLS}/requirements.txt

      ${CITOOLS}/scripts/what_changed.py -r ${MAIN_REPO_REPO_FULL_NAME} -p ${MAIN_REPO_PULL_REQUEST} --commits ${COMMIT_RANGE}


    displayName: Multiline Bash script
    env:
      name: Microsoft
