# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: a
  steps:
  - checkout: self
    fetchDepth: 1
    path: zephyr
  - bash: |
      echo SYSTEM_PULLREQUEST_PULLREQUESTNUMBER=${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER}
      git fetch origin pull/${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER}/head
      git checkout -f FETCH_HEAD
      export SHA=$(git rev-parse HEAD)
      echo SHA=${SHA}
      echo SYSTEM_PULLREQUEST_TARGETBRANCH=${SYSTEM_PULLREQUEST_TARGETBRANCH}
      git merge -q origin/${SYSTEM_PULLREQUEST_TARGETBRANCH}
      git rebase origin/${SYSTEM_PULLREQUEST_TARGETBRANCH}
      echo $(Build.Repository.Name)
      git log -5
      which bash
      echo "-- export --"
      export
      echo "--- PWD ---"
      pwd
      pip3 install setuptools wheel
      pip3 install west
      export PATH=$HOME/.local/bin:$PATH
      source zephyr-env.sh
      export COMMIT_RANGE=origin/${SYSTEM_PULLREQUEST_TARGETBRANCH}..HEAD
      west init -l . || true
      west update
      export CITOOLS=$(west list ci-tools -f"{abspath:18}")
      echo $CITOOLS
      sudo pip3 install -r ${CITOOLS}/requirements.txt

      ${CITOOLS}/scripts/what_changed.py -r ${BUILD_REPOSITORY_NAME} -p ${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER} --commits ${COMMIT_RANGE}


    displayName: Multiline Bash script
    env:
      name: Microsoft
