name: doc-build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
       DOXYGEN_VER: 1.8.16
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: install-pkg
      run: |
        sudo apt-get install -y ninja-build
    - name: build-requirements.txt
      run: |
         cp scripts/requirements.txt requirements.txt
    - name: cache-pip
      id: cache-pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    - name: cache-local
      id: cache-local
      uses: actions/cache@v1
      with:
        path: ~/.local
        key: ${{ runner.os }}-local-${{ hashFiles('requirements.txt') }}-${{ env.DOXYGEN_VER }}
    - name: install-pip
      if: steps.cache-pip.outputs.cache-hit != 'true' || steps.cache-local.outputs.cache-hit != 'true'
      run: |
        pip3 install setuptools
        pip3 install cmake
        pip3 install -r requirements.txt
    - name: install-doxygen
      if: steps.cache-local.outputs.cache-hit != 'true'
      run: |
        wget https://sourceforge.net/projects/doxygen/files/rel-${DOXYGEN_VER}/doxygen-${DOXYGEN_VER}.linux.bin.tar.gz
        tar xvf doxygen-${DOXYGEN_VER}.linux.bin.tar.gz
        mkdir -p ~/.local/bin
        cp doxygen-${DOXYGEN_VER}/bin/doxygen ~/.local/bin
    - name: cache-zephyr-modules
      uses: actions/cache@v1
      with:
        path: ../modules
        key: ${{ runner.os }}-zephyr-modules-${{ hashFiles('west.yml') }}
    - name: cache-zephyr-tools
      uses: actions/cache@v1
      with:
        path: ../tools
        key: ${{ runner.os }}-zephyr-tools-${{ hashFiles('west.yml') }}
    - name: build-docs
      run: |
        export PATH=$HOME/.local/bin:$PATH
        source zephyr-env.sh
        west init -l . || true
        west update
        make htmldocs
    - name: upload-log
      uses: actions/upload-artifact@master
      continue-on-error: True
      with:
        name: doc.warnings
        path: doc/_build/doc.warnings
#    - name: upload-docs
#      uses: actions/upload-artifact@master
#      continue-on-error: True
#      with:
#        name: htmldocs
#        path: doc/_build/html
    - name: export
      run: |
        export
