name: doc-build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: export
      run: |
        export      
    - uses: unacast/actions-github-deployment-status@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        status: FOO
