name: doc-build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: build-docs
      run: |
        echo "BUILD DOCS"
    - name: upload-log
      uses: actions/upload-artifact@master
      continue-on-error: True
      with:
        name: doc.warnings
        path: doc/_build/doc.warnings
    - name: export
      run: |
        export
