name: doc-build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    - uses: geekodour/gh-actions-custom-status@v0.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LAST_COMMIT_SHA: ${{ github.event.client_payload.LAST_COMMIT_SHA }}
      with:
       args: >-
         --state=pending
         --context=foo-status-update
         --target_url=https://github.com/${{ github.repository }}/actions
    steps:
    - uses: actions/checkout@v1
    - name: install-pkg
    - name: export
      run: |
        export 
